### ISSUE TITLE
TypeError: Components not found @dcl/ecs-scene-utils

### ISSUE THREAD

**Issue by jonaslund** [decentraland/decentraland-ecs-utils#28]
Importing the utils like 
```import * as utils from '@dcl/ecs-scene-utils'```

With the latest version, 1.7.2 and everything up to date
but getting this error

```TypeError: Components not found @dcl/ecs-scene-utils```

Also getting
```  Error /src/game.ts (2,24): Cannot find module '@dcl/ecs-scene-utils'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?```

In the build log, but it's in the node_modules, and has been installed with
```npm install @dcl/ecs-scene-utils```

Any ideas?

**Comment by jonaslund** [comment]
Adding 
``` 
 "bundleDependencies": [
    "@dcl/ecs-scene-utils"
  ]  
```
To the package.json resolves the issue.

Still, not entirley clear, it seems that if the triggerbox is outside of the parcel, it'll trigger an error, regardless.

**Comment by nearnshaw** [comment]
@jonaslund 
Did you install this library by running 
`npm install @dcl/ecs-scene-utils` ?

The right command to install it, as instructed in the docs, is 
`npm install @dcl/ecs-scene-utils -B`

That should in theory handle the bundleDependencies automatically
